### ISSUE TITLE
Missing random_pfnn files

### ISSUE THREAD

**Issue by Ericcsr** [facebookresearch/PhysicsVAE#1]
Hi, thanks for releasing code for this project! When running your code to collect expert data, it seems that
```
data/motion/pfnn/random_pfnn_0.bvh
```
is missing. How can I find it or how can I generate such file?

**Comment by nagooon** [comment]
Thanks for opening the code too! I seem to have the same problem... it'd be really nice if you could tell us how to find the file!

**Comment by Jungdam** [comment]
Hi all - Latest commits were missing while transferring my private repo to public one. Please check the current version, it should work now.
